using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading;
using System.Windows.Forms;

namespace AndroidToolsGUI
{
    public partial class Form1 : Form
    {
        private Process backendProcess = null;
        private Thread readThread = null;
        private bool isMonitoring = false;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            AppendLog("Android Multi Tools Classic GUI loaded.");
            AppendLog("Go Backend Binary expected: android_tools.exe");
            
            // Check if backend binary exists
            if (!File.Exists("android_tools.exe"))
            {
                AppendLog("WARNING: 'android_tools.exe' not found in this folder! Please place the compiled Go executable here.");
                MessageBox.Show("File 'android_tools.exe' tidak ditemukan di folder aplikasi ini.\nPastikan Anda menyalin file hasil compile Go ke folder ini.", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }

            // Load logo image dynamically
            try
            {
                if (File.Exists("Logo.jpeg"))
                {
                    picLogo.Image = System.Drawing.Image.FromFile("Logo.jpeg");
                }
                else if (File.Exists("download (1).png"))
                {
                    picLogo.Image = System.Drawing.Image.FromFile("download (1).png");
                }
                else
                {
                    AppendLog("INFO: No brand logo image found (Logo.jpeg or download (1).png).");
                }
            }
            catch (Exception ex)
            {
                AppendLog($"WARNING: Failed to load logo image: {ex.Message}");
            }
        }

        private void AppendLog(string text)
        {
            if (txtLog.InvokeRequired)
            {
                txtLog.Invoke(new Action<string>(AppendLog), text);
            }
            else
            {
                string timestamp = DateTime.Now.ToString("HH:mm:ss");
                txtLog.AppendText($"[{timestamp}] {text}{Environment.NewLine}");
                
                // Auto scroll to bottom
                txtLog.SelectionStart = txtLog.Text.Length;
                txtLog.ScrollToCaret();
            }
        }

        private void RunBackend(string arguments)
        {
            try
            {
                if (backendProcess != null && !backendProcess.HasExited)
                {
                    StopBackend();
                }

                ProcessStartInfo startInfo = new ProcessStartInfo
                {
                    FileName = "android_tools.exe",
                    Arguments = arguments,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    CreateNoWindow = true,
                    StandardOutputEncoding = Encoding.UTF8
                };

                backendProcess = new Process { StartInfo = startInfo };
                backendProcess.Start();

                isMonitoring = true;

                // Read output on a background thread to prevent GUI freezing
                readThread = new Thread(() =>
                {
                    using (StreamReader reader = backendProcess.StandardOutput)
                    {
                        string line;
                        while ((line = reader.ReadLine()) != null)
                        {
                            // Remove ANSI escape codes which might be generated by the Go terminal outputs
                            string cleanLine = RemoveAnsiEscapeCodes(line);
                            if (!string.IsNullOrWhiteSpace(cleanLine))
                            {
                                AppendLog(cleanLine);
                            }
                        }
                    }
                });
                readThread.IsBackground = true;
                readThread.Start();
            }
            catch (Exception ex)
            {
                AppendLog($"ERROR launching backend: {ex.Message}");
                ResetControlStates();
            }
        }

        private void StopBackend()
        {
            isMonitoring = false;
            try
            {
                if (backendProcess != null && !backendProcess.HasExited)
                {
                    backendProcess.Kill();
                    backendProcess.Dispose();
                }
            }
            catch { }
            backendProcess = null;
        }

        private string RemoveAnsiEscapeCodes(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            // Matches typical ANSI escape codes like \x1b[31m
            return System.Text.RegularExpressions.Regex.Replace(input, @"\x1B\[[^@-~]*[0-9A-Za-z]", "");
        }

        private void ResetControlStates()
        {
            if (this.InvokeRequired)
            {
                this.Invoke(new Action(ResetControlStates));
                return;
            }

            btnStartFastboot.Enabled = true;
            btnStopFastboot.Enabled = false;
            btnStartMtk.Enabled = true;
            btnStopMtk.Enabled = false;
            btnExtract.Enabled = true;
            btnExtract.Text = "Extract Now";
        }

        // --- Fastboot Monitor Buttons ---
        private void btnStartFastboot_Click(object sender, EventArgs e)
        {
            AppendLog("Starting Fastboot monitor...");
            btnStartFastboot.Enabled = false;
            btnStopFastboot.Enabled = true;
            btnStartMtk.Enabled = false; // Disable other monitor to prevent conflict

            RunBackend("fastboot");
        }

        private void btnStopFastboot_Click(object sender, EventArgs e)
        {
            AppendLog("Stopping Fastboot monitor...");
            StopBackend();
            ResetControlStates();
        }

        // --- MTK Monitor Buttons ---
        private void btnStartMtk_Click(object sender, EventArgs e)
        {
            AppendLog("Starting MediaTek (MTK) monitor...");
            btnStartMtk.Enabled = false;
            btnStopMtk.Enabled = true;
            btnStartFastboot.Enabled = false; // Disable other monitor

            RunBackend("mtk");
        }

        private void btnStopMtk_Click(object sender, EventArgs e)
        {
            AppendLog("Stopping MediaTek (MTK) monitor...");
            StopBackend();
            ResetControlStates();
        }

        // --- Extractor Tab Buttons ---
        private void btnBrowse_Click(object sender, EventArgs e)
        {
            using (OpenFileDialog openFileDialog = new OpenFileDialog())
            {
                openFileDialog.Filter = "Firmware Files (*.tar;*.tgz)|*.tar;*.tgz|All Files (*.*)|*.*";
                openFileDialog.Title = "Select Firmware Archive";

                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    txtFirmwarePath.Text = openFileDialog.FileName;
                    AppendLog($"Selected firmware path: {openFileDialog.FileName}");
                }
            }
        }

        private void btnExtract_Click(object sender, EventArgs e)
        {
            string path = txtFirmwarePath.Text.Trim();
            if (string.IsNullOrEmpty(path))
            {
                MessageBox.Show("Masukkan path file firmware terlebih dahulu!", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            AppendLog($"Executing firmware extraction: {path}");
            btnExtract.Enabled = false;
            btnExtract.Text = "Extracting...";

            // Launch extraction in background thread
            Thread extractThread = new Thread(() =>
            {
                try
                {
                    ProcessStartInfo startInfo = new ProcessStartInfo
                    {
                        FileName = "android_tools.exe",
                        Arguments = $"extract \"{path}\"",
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        CreateNoWindow = true,
                        StandardOutputEncoding = Encoding.UTF8
                    };

                    using (Process p = Process.Start(startInfo))
                    {
                        using (StreamReader reader = p.StandardOutput)
                        {
                            string line;
                            while ((line = reader.ReadLine()) != null)
                            {
                                string cleanLine = RemoveAnsiEscapeCodes(line);
                                if (!string.IsNullOrWhiteSpace(cleanLine))
                                {
                                    AppendLog(cleanLine);
                                }
                            }
                        }
                        p.WaitForExit();
                        
                        if (p.ExitCode == 0)
                        {
                            AppendLog("Extraction finished successfully.");
                        }
                        else
                        {
                            AppendLog($"Extraction finished with error. Exit code: {p.ExitCode}");
                        }
                    }
                }
                catch (Exception ex)
                {
                    AppendLog($"ERROR extracting: {ex.Message}");
                }
                finally
                {
                    ResetControlStates();
                }
            });
            extractThread.IsBackground = true;
            extractThread.Start();
        }

        private void btnClearLog_Click(object sender, EventArgs e)
        {
            txtLog.Clear();
            AppendLog("Logs cleared.");
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            StopBackend();
        }
    }
}
